### ISSUE TITLE
无法从Extension网站安装

### ISSUE THREAD

**Issue by wangzk** [wengxt/gnome-shell-extension-kimpanel#24]
今天上Gnome Shell Extension时，它提示kimpanel可以升级。但是升级后发现Extension网站自动删除了kimpanel。我手工去安装，它提示下载，但是下载后还是OFF的状态。请问一下，怎样才能看到具体是哪里出错了？谢！

Gnome Shell 3.8.3
Arch Linux

**Comment by wiiiky** [comment]
这应该只是网络问题，很多扩展都有这种问题
