### ISSUE TITLE
输入法光标指示小箭头不对齐

### ISSUE THREAD

**Issue by l0o0** [wengxt/gnome-shell-extension-kimpanel#35]
当输入栏靠近桌面边界的时候，有时候小箭头会对应不上。提示词一栏的小箭头和输入光标的位置不一致了

![image](https://user-images.githubusercontent.com/2743744/42493585-25004e8c-8450-11e8-9e0c-42b45624692b.png)

感觉这个issue角度有些刁钻

Ubuntu 18.04， fcitx 1:4.2.9.6-1，GNOME Shell 3.28.1， 从Gnome shell extension网站安装

**Comment by wengxt** [comment]
Fixed by https://github.com/wengxt/gnome-shell-extension-kimpanel/commit/45dc4e43caa5427272e3a46f359f72e8eeaa52a5
