### ISSUE TITLE
Candidate box disappear

### ISSUE THREAD

**Issue by ailinzhou** [wengxt/gnome-shell-extension-kimpanel#40]
If I enable this extension,The Candidate box disappear when I typing.
**Env**
`GNOME Shell 3.28.3`
`Ubuntu 18.04.1 LTS`
**Syslog**
De 30 22:48:56 zhou gnome-shell[1301]: JS ERROR: Exception in method call: SetSpotRect: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.setRect@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:324:13#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.SetSpotRect@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:328:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_handleMethodCall@resource:///org/gnome/gjs/modules/overrides/Gio.js:256:22#012_wrapJSObject/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:326:16
Dec 30 22:49:01 zhou gnome-shell[1301]: message repeated 9 times: [ JS ERROR: Exception in method call: SetSpotRect: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.setRect@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:324:13#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.SetSpotRect@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:328:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.]
Dec 30 22:49:02 zhou gnome-shell[1301]: JS ERROR: Exception in method call: SetLookupTable: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.SetLookupTable@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:340:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_handleMethodCall@resource:///org/gnome/gjs/modules/overrides/Gio.js:256:22#012_wrapJSObject/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:326:16
Dec 30 22:49:02 zhou gnome-shell[1301]: JS ERROR: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_parseSignal@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:179:17
Dec 30 22:49:03 zhou gnome-shell[1301]: message repeated 3 times: [ JS ERROR: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_parseSignal@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:179:17]
Dec 30 22:49:06 zhou gnome-shell[1301]: JS ERROR: Exception in method call: SetLookupTable: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.SetLookupTable@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:340:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_handleMethodCall@resource:///org/gnome/gjs/modules/overrides/Gio.js:256:22#012_wrapJSObject/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:326:16
Dec 30 22:49:06 zhou gnome-shell[1301]: JS ERROR: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_parseSignal@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:179:17
Dec 30 22:49:06 zhou gnome-shell[1301]: message repeated 3 times: [ JS ERROR: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_parseSignal@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:179:17]
Dec 30 22:49:06 zhou gnome-shell[1301]: JS ERROR: Exception in method call: SetLookupTable: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.SetLookupTable@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:340:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_handleMethodCall@resource:///org/gnome/gjs/modules/overrides/Gio.js:256:22#012_wrapJSObject/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:326:16
Dec 30 22:49:06 zhou gnome-shell[1301]: JS ERROR: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_parseSignal@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:179:17
Dec 30 22:49:06 zhou gnome-shell[1301]: JS ERROR: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_parseSignal@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:179:17
Dec 30 22:49:06 zhou gnome-shell[1301]: JS ERROR: Exception in method call: SetLookupTable: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.SetLookupTable@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:340:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_handleMethodCall@resource:///org/gnome/gjs/modules/overrides/Gio.js:256:22#012_wrapJSObject/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:326:16
Dec 30 22:49:06 zhou gnome-shell[1301]: JS ERROR: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_parseSignal@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:179:17
Dec 30 22:49:06 zhou gnome-shell[1301]: JS ERROR: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_parseSignal@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:179:17
Dec 30 22:49:06 zhou gnome-shell[1301]: JS ERROR: Exception in method call: SetLookupTable: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.SetLookupTable@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:340:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_handleMethodCall@resource:///org/gnome/gjs/modules/overrides/Gio.js:256:22#012_wrapJSObject/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:326:16
Dec 30 22:49:06 zhou gnome-shell[1301]: JS ERROR: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_parseSignal@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:179:17
Dec 30 22:49:07 zhou gnome-shell[1301]: message repeated 3 times: [ JS ERROR: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_parseSignal@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:179:17]
Dec 30 22:49:07 zhou gnome-shell[1301]: JS ERROR: Exception in method call: SetRelativeSpotRect: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.setRect@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:324:13#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.SetRelativeSpotRect@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:332:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_handleMethodCall@resource:///org/gnome/gjs/modules/overrides/Gio.js:256:22#012_wrapJSObject/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:326:16
Dec 30 22:49:30 zhou fcitx-autostart.desktop[1560]: (WARN-1615 x11selection.c:309) Selection is too long.
Dec 30 22:49:30 zhou gnome-shell[1301]: JS ERROR: Exception in method call: SetRelativeSpotRect: TypeError: global.display.get_monitor_index_for_rect is not a function#012InputPanel<.updatePosition@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:192:51#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.updateInputPanel@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:299:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.setRect@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:324:13#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012Kimpanel<.SetRelativeSpotRect@/home/ailin/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:332:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_handleMethodCall@resource:///org/gnome/gjs/modules/overrides/Gio.js:256:22#012_wrapJSObject/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:326:16

**Comment by shlinux** [comment]
[](https://github.com/wengxt/kimpanel-for-gnome-shell/commit/a8363569abb64e9878b06deb6583fb2de7179de4)
