### ISSUE TITLE
opensuseleap15.1上存在问题

### ISSUE THREAD

**Issue by SoloGiant** [wengxt/gnome-shell-extension-kimpanel#43]
在leap15.1上安装后，选词栏消失。

**Comment by wengxt** [comment]
what's the version of gnome-shell?

**Comment by SoloGiant** [comment]
gnome 3.26.2，输入法fcitx-rime，Debian testing下相同输入法没有问题。

**Comment by Alexander-Huang** [comment]
相似的问题，选词栏背景变成全透明，字体为白色，输入法设置外观项显示“kimpanel无配置选项”。关闭该扩展后显示正常。
fcitx版本：4.2.97
gnome-shell版本：3.36
该扩展版本：47

**Comment by DREAMSKYWORLD** [comment]
选词栏背景和gnome-shell主题有关，你可以选择不同的gnome-shell主题试试。输入法设置外观显示“kimpanel无配置选项"。不能使用fcitx皮肤和相关字体设置失效。希望可以只将输入法状态栏集成到gnome-shell，不影响皮肤和字体设置。
fcitx版本： 4.2.9.7
gnome-shell版本： 3.36

**Comment by Alexander-Huang** [comment]
> 选词栏背景和gnome-shell主题有关，你可以选择不同的gnome-shell主题试试。输入法设置外观显示“kimpanel无配置选项"。不能使用fcitx皮肤和相关字体设置失效。希望可以只将输入法状态栏集成到gnome-shell，不影响皮肤和字体设置。
> fcitx版本： 4.2.9.7
> gnome-shell版本： 3.36

same issue.

**Comment by Alexander-Huang** [comment]
> > 选词栏背景和gnome-shell主题有关，你可以选择不同的gnome-shell主题试试。输入法设置外观显示“kimpanel无配置选项"。不能使用fcitx皮肤和相关字体设置失效。希望可以只将输入法状态栏集成到gnome-shell，不影响皮肤和字体设置。
> > fcitx版本： 4.2.9.7
> > gnome-shell版本： 3.36
> 
> same issue，Archlinux with gnome shell 3.36,fcitx 4.2.9.7-3 and extension version 49 coming from https://extensions.gnome.org/extension/261/kimpanel/

**Comment by wengxt** [comment]
> > 选词栏背景和gnome-shell主题有关，你可以选择不同的gnome-shell主题试试。输入法设置外观显示“kimpanel无配置选项"。不能使用fcitx皮肤和相关字体设置失效。希望可以只将输入法状态栏集成到gnome-shell，不影响皮肤和字体设置。
> > fcitx版本： 4.2.9.7
> > gnome-shell版本： 3.36
> 
> same issue.

你用什么主题？

> 选词栏背景和gnome-shell主题有关，你可以选择不同的gnome-shell主题试试。输入法设置外观显示“kimpanel无配置选项"。不能使用fcitx皮肤和相关字体设置失效。希望可以只将输入法状态栏集成到gnome-shell，不影响皮肤和字体设置。
> fcitx版本： 4.2.9.7
> gnome-shell版本： 3.36

如果需要托盘图标你可以装 app indicator 。

**Comment by wengxt** [comment]
> > 选词栏背景和gnome-shell主题有关，你可以选择不同的gnome-shell主题试试。输入法设置外观显示“kimpanel无配置选项"。不能使用fcitx皮肤和相关字体设置失效。希望可以只将输入法状态栏集成到gnome-shell，不影响皮肤和字体设置。
> > fcitx版本： 4.2.9.7
> > gnome-shell版本： 3.36
> 
> same issue.

gnome-shell插件那边可以配置字体。文本颜色的话老实说没有特别设置，应该能跟随主题走才对。
和 fcitx 皮肤无关那是本来就是如此设计的。

**Comment by RRRRRm** [comment]
> > > 选词栏背景和gnome-shell主题有关，你可以选择不同的gnome-shell主题试试。输入法设置外观显示“kimpanel无配置选项"。不能使用fcitx皮肤和相关字体设置失效。希望可以只将输入法状态栏集成到gnome-shell，不影响皮肤和字体设置。
> > > fcitx版本： 4.2.9.7
> > > gnome-shell版本： 3.36
> > 
> > 
> > same issue.
> 
> gnome-shell插件那边可以配置字体。文本颜色的话老实说没有特别设置，应该能跟随主题走才对。
> 和 fcitx 皮肤无关那是本来就是如此设计的。

请问可以强制指定颜色吗, 应该修改哪个部分?

**Comment by RRRRRm** [comment]
> > > 选词栏背景和gnome-shell主题有关，你可以选择不同的gnome-shell主题试试。输入法设置外观显示“kimpanel无配置选项"。不能使用fcitx皮肤和相关字体设置失效。希望可以只将输入法状态栏集成到gnome-shell，不影响皮肤和字体设置。
> > > fcitx版本： 4.2.9.7
> > > gnome-shell版本： 3.36
> > 
> > 
> > same issue.
> 
> gnome-shell插件那边可以配置字体。文本颜色的话老实说没有特别设置，应该能跟随主题走才对。
> 和 fcitx 皮肤无关那是本来就是如此设计的。

我大概看了一下, 应该是项目里的那个CSS文件, 不过我还没试出来怎么改.

**Comment by RRRRRm** [comment]
> > > 选词栏背景和gnome-shell主题有关，你可以选择不同的gnome-shell主题试试。输入法设置外观显示“kimpanel无配置选项"。不能使用fcitx皮肤和相关字体设置失效。希望可以只将输入法状态栏集成到gnome-shell，不影响皮肤和字体设置。
> > > fcitx版本： 4.2.9.7
> > > gnome-shell版本： 3.36
> > 
> > 
> > same issue.
> 
> gnome-shell插件那边可以配置字体。文本颜色的话老实说没有特别设置，应该能跟随主题走才对。
> 和 fcitx 皮肤无关那是本来就是如此设计的。

好像选中部分的背景是 `.kimpanel-candidate-item:active`
未选中部分的背景和文字的颜色还没试出来, 大哥能不能帮忙看一下

**Comment by chenzaichun** [comment]
同样的问题，暗色主题下，如果输入的背景是白色或者亮色，那么完全看不清楚。

**Comment by wengxt** [comment]
@chenzaichun 哪个主题…gnome shell 默认不就是暗色么

**Comment by chenzaichun** [comment]
换了一个其他的主题: `WhiteSur-dark`， 这个主题应该是不完整的，所以不行（没有背景框，造成在白色的背景下完全看不清楚），默认的暗色主题是可以的，比如 `Yaru`。我现在切换回 `Yaru` 了

**Comment by wengxt** [comment]
@chenzaichun ^ 测试了一下，WhiteSur-dark 也没有问题了
