### ISSUE TITLE
fcitx5 support????

### ISSUE THREAD

**Issue by devillove084** [wengxt/gnome-shell-extension-kimpanel#44]
This extension does not support for fcitx5.

**Comment by wengxt** [comment]
It should, though I never test it.

What did you get?

**Comment by wengxt** [comment]
It does work with fcitx5. Probably a config issue on your side.

**Comment by limon** [comment]
The tray icon does not change when I switch Input Methods

openSUSE Tumbleweed Gnome 3.36
