### ISSUE TITLE
2 keyboard selectors visible

### ISSUE THREAD

**Issue by Dreamsorcerer** [wengxt/gnome-shell-extension-kimpanel#48]
Given that the original keyboard selector only works if using ibus, I think it would be a good idea if this extension removed the old selector when enabled. This would make the user experience more seamless.

Could maybe use some code from this extension to achieve that: https://extensions.gnome.org/extension/2848/hide-keyboard-layout/

**Comment by wengxt** [comment]
You should uninstall ibus actually. Though sometimes you can't control due to how the package is done.

Fcitx 5 will ask ibus to exit. I don't want to do anything to hack built-in gnome-shell feature. It would be easily break by upstream.

**Comment by Dreamsorcerer** [comment]
I uninstalled ibus already. The keyboard selector still appears.

That other extension I mentioned, looking at the code, it appears to be little more than a line of code, so probably not a major dependency on upstream (though maybe they should ensure it's hidden upstream when ibus isn't running).

```
let keyboard = Main.panel.statusArea.keyboard
let watching

function enable () {
  keyboard.hide()
  watching = keyboard.actor.connect('notify::visible', actor => {
    actor.hide()
  })
}

function disable () {
  if (watching) keyboard.actor.disconnect(watching)
  keyboard.show()
}
```

**Comment by wengxt** [comment]
you can remove all the input source in gnome-control-center.

**Comment by wengxt** [comment]
Such monkey patching would be fragile because it's not a public gnome-shell api. I won't do that.
