### ISSUE TITLE
Input doesn't work in the shell.

### ISSUE THREAD

**Issue by Dreamsorcerer** [wengxt/gnome-shell-extension-kimpanel#50]
fcitx doesn't seem to work in the shell itself (e.g. when searching for an application).

Maybe that's not an issue for the extension, I'm not sure.

**Comment by wengxt** [comment]
The shell itself is hardcoded to only use ibus. This is irrelevant to this ext.

You may use fcitx5 (which support to simulate itself to be ibus).
