### ISSUE TITLE
no popup window when typing

### ISSUE THREAD

**Issue by szcf-weiya** [wengxt/gnome-shell-extension-kimpanel#53]
I am using gnome-shell 3.28.4 on Ubuntu 18.04.5, and I install the extension via browser extensions. The input methods I am using are google-pinyin and rime with fcitx-4.2.9.6. Before enabling the kimpanel extension, all work well, 

![Peek 2021-04-03 12-35](https://user-images.githubusercontent.com/13688320/113468484-10476480-9479-11eb-9431-b499319df683.gif)

but after enabling this extension, no popup windows when inputting, just as shown in the following gif, where I type "fcitx" with google-pinyin in a LibreOffice document,
![Peek 2021-04-03 12-12](https://user-images.githubusercontent.com/13688320/113467636-decd9980-9476-11eb-8ca1-56c7e0209192.gif)

Interestingly, I found that if I type in the search box (press the `Win` key), the popup window appears,
![Screenshot from 2021-04-03 12-11-59](https://user-images.githubusercontent.com/13688320/113467692-44218a80-9477-11eb-832a-de1f66b5857a.png)
and it seems that the input method are different from google-pinyin since different candidates.

**Comment by wengxt** [comment]
The later one is ibus. Gnome shell search box is hardcode to use ibus.

As for you issue itself, I don't have a system with corresponding version of gnome-shell. The gnome shell break the compatiblity all the time, so I don't really know which commit works for you.

From the comment it might be some comment among them:
<img width="784" alt="图片" src="https://user-images.githubusercontent.com/259684/113468933-4c89af00-93fe-11eb-8770-aa913d5bf4ab.png">

**Comment by szcf-weiya** [comment]
Thanks for your kind explanation.
