### ISSUE TITLE
顶栏图标有些不对齐

### ISSUE THREAD

**Issue by kkren** [wengxt/gnome-shell-extension-kimpanel#54]
![图片](https://user-images.githubusercontent.com/23287823/115069858-c81f4c00-9f26-11eb-891b-bd7a427550b3.png)
![图片](https://user-images.githubusercontent.com/23287823/115070004-f4d36380-9f26-11eb-88d0-9b5b0106febd.png)

强迫症看的很难受

**Comment by rocka** [comment]
用 looking glass 看了一下发现这不是图标，其实是文字 label

https://github.com/wengxt/gnome-shell-extension-kimpanel/blob/63a7e009502024100d35d52f0f90de46cfb6aa65/indicator.js#L127-L137

这段代码提取出了 `label=` 之后的文字后就 return 了，后续判断 iconName 并 createIcon 的部分被略过了 ...

**Comment by wengxt** [comment]
没得办法。

**Comment by wengxt** [comment]
或者换句话说，gnome + ibus 反正也是这样，我只是忠实再现 gnome 自己的 style 而已
