### ISSUE TITLE
appindicator也会显示fcitx5图标，能否加个开关去除现有的图标

### ISSUE THREAD

**Issue by woqulegenicheng** [wengxt/gnome-shell-extension-kimpanel#56]
![图片](https://user-images.githubusercontent.com/34201719/115131428-a7401f00-a02a-11eb-828f-c14a0dbbd007.png)

**Comment by wengxt** [comment]
你这哪个图标是 appindicator 显示给的 fcitx 的？

如果用 kimpanel 的时候还有 appindicator 的 fcitx 图标那是 bug

**Comment by woqulegenicheng** [comment]
最左边那个，appindicator的图标会在锁屏后再次出现。
锁屏前：
![图片](https://user-images.githubusercontent.com/34201719/115132508-8f20cd80-a033-11eb-837e-d355a071e39c.png)
锁屏再解锁后：
![图片](https://user-images.githubusercontent.com/34201719/115132516-a2339d80-a033-11eb-8720-11ed0e118314.png)

也许是加载顺序的问题？

**Comment by plumlis** [comment]
你点重新启动看是不是还有俩图标
如果重新启动正常的话你可以设定 fcitx 的延后启动

**Comment by woqulegenicheng** [comment]
点重新启动或者alt+f2输入r后appindicator所带来的图标会消失，如何在锁屏解锁后自动重新启动fcitx5？因为锁屏时fcitx5仍在运行。

**Comment by wengxt** [comment]
@plumlis ……bug 就是 bug 能不能不要说什么这么奇怪的 workaround 啊……

不过非要说的话我印象中是和 appindicator 的实现可能有关系，尽管我尝试注销了服务隐藏图标，但是没有成功走到让它隐藏图标的代码去

**Comment by wengxt** [comment]
not a bug of this extension.

**Comment by wengxt** [comment]
非要说的话，是 https://github.com/ubuntu/gnome-shell-extension-appindicator/ 的 bug，因为即使服务消失了它也不去掉对应的图标（KDE的实现就完全没有问题）。不过可以在 fcitx workaround 一下。

**Comment by wengxt** [comment]
因为 https://github.com/ubuntu/gnome-shell-extension-appindicator/ 即使你用 service name 注册，它也只靠监听 unique name 来判断程序的退出与否
