### ISSUE TITLE
Candidate box stays at screen

### ISSUE THREAD

**Issue by nexustar** [wengxt/gnome-shell-extension-kimpanel#57]
if type but not select character,then lock the screen, the candidate box stays at screen after unlock

Environment:
debian 11, gnome, gdm, fcitx5

**Comment by plumlis** [comment]
Same here
Fedora 34 64bit Gnome 40.4

- Type something and keep select candidate box display
- Press Super+L to lock the screen
- Unlock and login you will see candidate box stay on screen

![Screenshot from 2021-09-01 16-08-54](https://user-images.githubusercontent.com/6737429/131636776-176f179f-9ea5-4447-9f67-e4c30e779b9c.png)

**Comment by oeyoews** [comment]
> Same here
> Fedora 34 64bit Gnome 40.4
> 
> * Type something and keep select candidate box display
> * Press Super+L to lock the screen
> * Unlock and login you will see candidate box stay on screen
> 
> ![Screenshot from 2021-09-01 16-08-54](https://user-images.githubusercontent.com/6737429/131636776-176f179f-9ea5-4447-9f67-e4c30e779b9c.png)

just restart fcitx5

**Comment by wengxt** [comment]
Should be fixed by now.
