### ISSUE TITLE
能否自己更改颜色

### ISSUE THREAD

**Issue by oeyoews** [wengxt/gnome-shell-extension-kimpanel#63]
- 可以更改输入法文字的背景颜色吗？

**Comment by plumlis** [comment]
我觉得样式应该是继承自 Gnome-shell 气泡主题的
你可以尝试换个 Gnome-shell 主题。

**Comment by wengxt** [comment]
只能说你可以自己写 css ……我给文本定义了单独的 class 你可以给它单独设置颜色

**Comment by Sherlock-Holo** [comment]
css ![打包](https://aur.archlinux.org/packages/gnome-shell-extension-kimpanel-git)时放进了 `/usr/share/gnome-shell/extensions/kimpanel@kde.org/stylesheet.css` 这里，有没有什么办法让 kimpanel 读取自己 home 目录下的 stylesheet.css 去覆盖这个默认配置
