### ISSUE TITLE
TrueType 字体无效

### ISSUE THREAD

**Issue by sommio** [wengxt/gnome-shell-extension-kimpanel#73]
来源：ALHP, archlinuxcn
```
ttf-sarasa-gothic                  0.40.6-1
fcitx5                             5.0.23-1.1 (fcitx5-im)
gnome-shell-extensions             44.0-1
gnome-shell-extension-kimpanel-git 20220302-5
```

![_ovVqg](https://user-images.githubusercontent.com/64189793/236697139-30c684ab-d74d-410b-bdb7-6b01a8a63a18.jpg)
![x3KbhB](https://user-images.githubusercontent.com/64189793/236697524-c5d2b47b-e3eb-45ea-b147-bff179095841.jpg)

**实际无效**

**Comment by JoveYu** [comment]
我使用思源黑体设置也是无效，猜测是中文字体名称不识别，强制改成字体英文名称后有效果
