### ISSUE TITLE
如何调整候选词边框的圆角半径？

### ISSUE THREAD

**Issue by linsui** [wengxt/gnome-shell-extension-kimpanel#74]
外侧的半径太大，我想要调整到和选中的候选词高亮的圆角相近。请问怎样修改？谢谢

**Comment by wengxt** [comment]
stylesheet.css

**Comment by linsui** [comment]
我没有找到外边框要改哪个 class，最后把选中的高亮圆角改到 8px 了。

**Comment by linsui** [comment]
不知道为什么 GNOME 45 上没有这个问题，我现在就用原本的样式看着就挺和谐了。

**Comment by wengxt** [comment]
因为样式改过了？
https://github.com/wengxt/gnome-shell-extension-kimpanel/pull/71
