### ISSUE TITLE
Stop working on Gnome 45 final release

### ISSUE THREAD

**Issue by plumlis** [wengxt/gnome-shell-extension-kimpanel#77]
Gnome 45 is released today. But this extension no longer working.

Installed Gnome-45  Ported branch. Version 77

JS ERROR: Extension kimpanel@kde.org: TypeError: (intermediate value).Align is undefined
_init@file:///home/plum/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:27:49
InputPanel@file:///home/plum/.local/share/gnome-shell/extensions/kimpanel@kde.org/panel.js:16:8
_init@file:///home/plum/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:97:27
Kimpanel@file:///home/plum/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:77:1
enable@file:///home/plum/.local/share/gnome-shell/extensions/kimpanel@kde.org/extension.js:357:24
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:252:38
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:461:32
async*_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:759:24
async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:765:48
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:800:20
async*init@resource:///org/gnome/shell/ui/extensionSystem.js:71:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:291:22
start@resource:///org/gnome/shell/ui/main.js:164:11
@resource:///org/gnome/shell/ui/init.js:11:47
@resource:///org/gnome/shell/ui/init.js:21:20

**Comment by plumlis** [comment]
It seems  St.Align type has been removed from gnome-shell. should use Clutter.ActorAlign instead.

**Comment by wengxt** [comment]
what the fuck are they doing? like changing API at beta? It was tested well on 45.beta

**Comment by plumlis** [comment]
Yeah. It works well on 45.beta. But not on 45  release version.

https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2936

**Comment by Sherlock-Holo** [comment]
archlinux has updated gnome-shell to 45, and I rebuild gnome-shell-extension-kimpanel-git with latest codes(also I rebooted archlinux), however it still report 
![image](https://github.com/wengxt/gnome-shell-extension-kimpanel/assets/10096425/b84eec9b-7f28-4bf5-b024-e39a66cd41ac)
