### ISSUE TITLE
"#77 not fixed" version is now selectable for Gnome 45

### ISSUE THREAD

**Issue by mikunimaru** [wengxt/gnome-shell-extension-kimpanel#80]
Please enable installation of only versions after the fix #77 has been completed.
If a non-working version is placed, users who install it incorrectly will be in trouble. I was one of them.

**Comment by wengxt** [comment]
I'm pretty sure the latest version on gnome shell extension is the fixed version. Are you downloading the wrong version?

The version 79 on gnome shell extension is the one you want
