### ISSUE TITLE
what happen

### ISSUE THREAD

**Issue by miaobuao** [wengxt/gnome-shell-extension-kimpanel#82]
## system info

 OS: Fedora Linux 40 (Workstation Editi 

Kernel: 6.8.7-300.fc40.x86_64 

DE: GNOME 46.1 

![image](https://github.com/wengxt/gnome-shell-extension-kimpanel/assets/62047803/bf7d1335-560b-4ae3-ac30-1883a7027283)

**Comment by plumlis** [comment]
I have same OS and Gnome version. Fedora 40 with Gnome 46.1 and wayland
But no issue with kimpanel.
Can you try to uninstall totally and install again?

**Comment by miaobuao** [comment]
Uninstall, restart, and then reinstall, but this issue still persists 😭

**Comment by plumlis** [comment]
How about use dconf-editor and check this path?
/org/gnome/shell/extensions/kimpanel/

**Comment by miaobuao** [comment]
Oh, you're right. When I configure it like this, the error disappears
![image](https://github.com/wengxt/gnome-shell-extension-kimpanel/assets/62047803/d3f43ada-7e77-44db-9d75-1d2847323a7a)

The error occurred when I was using this font: 
![image](https://github.com/wengxt/gnome-shell-extension-kimpanel/assets/62047803/98929f48-8a4f-4ad5-98bb-a9948908743d)

Thank you for your help. This issue may be closed now : )

**Comment by plumlis** [comment]
Seems kimpanel's configuration doesn't support variable font yet.

**Comment by miaobuao** [comment]
However, it's amazing that when I use `MiSans VF Regular`, there won't be any errors😂
![image](https://github.com/wengxt/gnome-shell-extension-kimpanel/assets/62047803/99557832-b870-41f3-a9d2-992b25c826d3)
