### ISSUE TITLE
是否可以加一个默认的亮色和暗色主题，根据gnome/fcitx5当前主题自动切换？

### ISSUE THREAD

**Issue by xcpky** [wengxt/gnome-shell-extension-kimpanel#84]
当前在gnome下输入法框背景是黑色的，能不能做一个白色背景的的并根据fcitx5或者gnome的当前主题切换呢？ 而且fcitx5设置里是有跟随gnome当前主题的选项的。

**Comment by plumlis** [comment]
其实目前就是跟随gnome主题切换的，但是gnomeshell官方就是黑色。你用ubuntu带白色的就发现变白色了。

**Comment by xcpky** [comment]
> 其实目前就是跟随gnome主题切换的，但是gnomeshell官方就是黑色。你用ubuntu带白色的就发现变白色了。

gnome-shell 默认的dark mode和light mode都是黑的吗，我是想跟随dark/light mode

**Comment by plumlis** [comment]
我没记错的话目前gnomeshell还没有light theme
大概就是你点顶栏菜单，下拉是什么颜色的窗口，输入法就是什么颜色

**Comment by CSUDaXiang** [comment]
@xcpky @plumlis 安装了这个插件后，使用了这个kde界面，是不是只能使用默认安装的输入法主题呀，不能更改输入法的皮肤吗？

**Comment by plumlis** [comment]
> @xcpky @plumlis 安装了这个插件后，使用了这个kde界面，是不是只能使用默认安装的输入法主题呀，不能更改输入法的皮肤吗？

这是 gnome-shell 的插件，哪儿有什么 KDE 的东西，KDE 有另外一套显示界面和插件。
这个就是只能用和 Gnome-shell 主题一样的风格，如果你想换皮肤，就别装这个，用 fcitx 自己的界面。

**Comment by CSUDaXiang** [comment]
@xcpky 好的，明白。再想请教一下，用这个插件后，输入法的界面有这个倒三角形，有没有办法可以把这个倒三角形去掉，只显示上面的长方形框。
![image](https://github.com/user-attachments/assets/3ec22e22-d09c-499c-b3cf-a6154dc2aecc)

**Comment by plumlis** [comment]
> @xcpky 好的，明白。再想请教一下，用这个插件后，输入法的界面有这个倒三角形，有没有办法可以把这个倒三角形去掉，只显示上面的长方形框。 ![image](https://private-user-images.githubusercontent.com/28582507/355307915-3ec22e22-d09c-499c-b3cf-a6154dc2aecc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzY4OTUsIm5iZiI6MTcyMjkzNjU5NSwicGF0aCI6Ii8yODU4MjUwNy8zNTUzMDc5MTUtM2VjMjJlMjItZDA5Yy00OTljLWIzY2YtYTYxNTRkYzJhZWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA5Mjk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMmJiZDY5ZDcxNGNmMWIwNjRjMWFkOWNmZGI0NDFkN2VmZDgxZTk3MzNmOGE1NDM4OGE1Yzk0M2IwZGE5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J1l6WYxVd4_wo-Niu0ZHuJbisxACrabHxOmxNIIeMiA)

我懂你意思，但是这个是去不掉的。这个和你的 Gnome-Shell 主题有关，这个插件只是借用了 Gnome-shell 主题里的 pop 气泡元素而已。

官方的 Gnome-shell 默认主题是没有这个箭头的，所以显示正常。我不记得 Ubuntu 的 yaru 有没有了。

解决办法就是要么别用这个插件，要么你换个 Gnome-shell 的主题。
