### ISSUE TITLE
Candidate list window not positioned correctly for Xwayland windows with Gnome 47 'xwayland-native-scaling' enabled

### ISSUE THREAD

**Issue by struq** [wengxt/gnome-shell-extension-kimpanel#86]
Gnome 47 has a new experimental option to allow Xwayland apps to use their native HiDPI scaling to avoid blurriness under fractional scaling (https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3567). When this is enabled, kimpanel does not place the candidate list window correctly under the cursor for Xwayland windows. Using fcitx without kimpanel does not have this issue.

Steps to reproduce:
1. Run mutter and gnome-settings-daemon version > 47.rc
2. Enable xwayland-native-scaling for mutter 
 `gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer','xwayland-native-scaling']"`
3. Set display scaling to 175% in gnome-control-center, or any other values higher than 100%
4. Open an Xwayland app and type inside with fcitx & kimpanel

Related:
fix for IBus https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3458 

Screenshots:
'xwayland-native-scaling' enabled, candidate list window position not under the cursor:
![xwayland_native_scaling_enabled](https://github.com/user-attachments/assets/79cfa790-6902-4749-a7e5-25f55d71cad9)
'xwayland-native-scaling' disabled (but 'scale-monitor-framebuffer' still enabled), correct candidate list window position but blurry Xwayland window:
![xwayland_native_scaling_disabled](https://github.com/user-attachments/assets/414ca901-77e5-467f-8b14-193aab07ee2c)

**Comment by plumlis** [comment]
Same here.
Disable extension and use original candidate list seems fine.

**Comment by 7HE-W0R1D** [comment]
I'm on version 84 that I installed from gnome extensions website, and the problem still persists, should I install it from source to make it work? Thank you!

**Comment by plumlis** [comment]
> I'm on version 84 that I installed from gnome extensions website, and the problem still persists, should I install it from source to make it work? Thank you!

I'm on version 84 and gnome 47 with 'scale-monitor-framebuffer','xwayland-native-scaling' enabled.

Works fine on my pc.

Could you share up your DE and Distro version?

**Comment by 7HE-W0R1D** [comment]
> > I'm on version 84 that I installed from gnome extensions website, and the problem still persists, should I install it from source to make it work? Thank you!
> 
> I'm on version 84 and gnome 47 with 'scale-monitor-framebuffer','xwayland-native-scaling' enabled.
> 
> Works fine on my pc.
> 
> Could you share up your DE and Distro version?

I'm on fedora silverblue 41 and gnome 47.

**Comment by 7HE-W0R1D** [comment]
For reference, here's the panel position with and without the extension:
![image](https://github.com/user-attachments/assets/46265e51-29b4-4c1c-a79f-1a05a9595847)
![image](https://github.com/user-attachments/assets/7998ac8c-40c7-46cf-8444-a016e7fef3e6)

**Comment by wengxt** [comment]
@7HE-W0R1D , did you set QT_IM_MODULE=fcitx ?

**Comment by 7HE-W0R1D** [comment]
> @7HE-W0R1D , did you set QT_IM_MODULE=fcitx ?

I unset it to test but I reset it before I managed to get it working. Is unsetting it the right thing to do?

**Comment by howdev** [comment]
This still happens in Ubuntu 24.04 Gnome 46 wayland fractional scaling. 

1. Gnome terminal - popup is away from the cursor. 
2. chrome based browser, in the webage inputboxes, popup overlaps the cursor.
