### ISSUE TITLE
鼠标点击输入法的图标，菜单选项有的时候显示不完全

### ISSUE THREAD

**Issue by CSUDaXiang** [wengxt/gnome-shell-extension-kimpanel#87]
GNOME 3.36版本，在中文拼音输入法时，鼠标点击输入法的图标，有的时候显示的图标是这样的：
![image](https://github.com/user-attachments/assets/5d7c98d1-f399-4eb1-bbcc-05ce200ec1f3)
而有的时候显示不全，显示成这样的：
![image](https://github.com/user-attachments/assets/94b29951-0744-42bc-8ab5-6bda4cfc4fe1)
不太清楚这是哪块的问题，看了半天源码也没发现什么问题，有人遇到过这个问题吗？

**Comment by plumlis** [comment]
先说说你的发行版吧，还有从哪里安装的fcitx，
感觉像是后者输入法是非启用状态。

这个应该也和这个插件没啥关系，你把插件关了直接点击原来的trayicon看看

**Comment by CSUDaXiang** [comment]
@plumlis  发行版是ubuntu20.04，通过apt源安装的5.0.17版本的fcitx5.

输入法是正常启用的，都是可以正常打字的。
![image](https://github.com/user-attachments/assets/45dea0fe-8b44-4f5a-b584-8463dedbcd3c)

禁用插件直接用系统的托盘显示是正常的，不会出现我说的这种情况。
![image](https://github.com/user-attachments/assets/b8ae5c13-50aa-4777-9bff-3f568bc63f6f)

**Comment by CSUDaXiang** [comment]
@plumlis 后端输入法是正常的，通过dbus-monitor监控dbus信号，是有这些菜单选项的，只是前端插件有的时候没有显示出来。
signal time=1726652001.193221 sender=:1.500 -> destination=(null destination) serial=9595 path=/kimpanel; interface=org.kde.kimpanel.inputmethod; member=UpdateProperty
   string "/Fcitx/im:拼音:fcitx5-pinyin::menu,label=拼"
signal time=1726652001.193242 sender=:1.500 -> destination=(null destination) serial=9596 path=/kimpanel; interface=org.kde.kimpanel.inputmethod; member=Enable
   boolean true
signal time=1726652001.194442 sender=:1.500 -> destination=(null destination) serial=9600 path=/kimpanel; interface=org.kde.kimpanel.inputmethod; member=RegisterProperties
   array [
      string "/Fcitx/im:拼音:fcitx5-pinyin::menu,label=拼"
      string "/Fcitx/chttrans:简体中文:fcitx5-chttrans-inactive::"
      string "/Fcitx/punctuation:全角标点:fcitx5-punc-active::"
      string "/Fcitx/fullwidth:半角字符:fcitx5-fullwidth-inactive::"
      string "/Fcitx/pinyin-prediction:预测:fcitx5-remind-inactive:显示联想词组:"
   ]
signal time=1726652001.194495 sender=:1.500 -> destination=(null destination) serial=9601 path=/kimpanel; interface=org.kde.kimpanel.inputmethod; member=UpdateProperty
   string "/Fcitx/im:拼音:fcitx5-pinyin::menu,label=拼"
signal time=1726652001.194511 sender=:1.500 -> destination=(null destination) serial=9602 path=/kimpanel; interface=org.kde.kimpanel.inputmethod; member=Enable
   boolean true
signal time=1726652001.194523 sender=:1.500 -> destination=(null destination) serial=9603 path=/kimpanel; interface=org.kde.kimpanel.inputmethod; member=UpdateProperty
   string "/Fcitx/im:拼音:fcitx5-pinyin::menu,label=拼"
signal time=1726652001.194540 sender=:1.500 -> destination=(null destination) serial=9604 path=/kimpanel; interface=org.kde.kimpanel.inputmethod; member=Enable
   boolean true
signal time=1726652001.194577 sender=:1.500 -> destination=(null destination) serial=9606 path=/kimpanel; interface=org.kde.kimpanel.inputmethod; member=RegisterProperties
   array [
      string "/Fcitx/im:拼音:fcitx5-pinyin::menu,label=拼"
      string "/Fcitx/chttrans:简体中文:fcitx5-chttrans-inactive::"
      string "/Fcitx/punctuation:全角标点:fcitx5-punc-active::"
      string "/Fcitx/fullwidth:半角字符:fcitx5-fullwidth-inactive::"
      string "/Fcitx/pinyin-prediction:预测:fcitx5-remind-inactive:显示联想词组:"
   ]
signal time=1726652001.194609 sender=:1.500 -> destination=(null destination) serial=9607 path=/kimpanel; interface=org.kde.kimpanel.inputmethod; member=UpdateProperty
   string "/Fcitx/im:拼音:fcitx5-pinyin::menu,label=拼"
signal time=1726652001.194618 sender=:1.500 -> destination=(null destination) serial=9608 path=/kimpanel; interface=org.kde.kimpanel.inputmethod; m

**Comment by wengxt** [comment]
建议先更新fcitx看看
